name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enable Docker Buildx

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Stored as a GitHub Action secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Stored as a GitHub Action secret (your PAT)

      - name: Build Docker image
        run: docker build -t rvnn/music-recommender:latest .  # Replace with your Docker Hub repo name

      - name: Push Docker image
        run: docker push rvnn/music-recommender:latest  # Push to Docker Hub
